-- 100 seed products covering: all statuses, featured/non-featured,
-- price range (9.99–1499.99), multiple currencies, short/long descriptions.
-- Status split: 55 IN_STOCK · 30 OUT_OF_STOCK · 15 DISCONTINUED
-- Featured: 15 products spread across statuses and categories

INSERT INTO products (product_number, title, description, price, currency, status, featured, instagram_post_url) VALUES

-- ── SNEAKERS / SHOES (PN-001 – PN-020) ───────────────────────────────────────
('PN-001', 'Air Stride Pro', 'Lightweight running shoe with responsive foam midsole and breathable mesh upper. Ideal for daily training runs and casual wear.', 129.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed001/'),
('PN-002', 'Urban Runner X', 'Street-ready sneaker combining heritage silhouette with modern cushioning. Available in six colorways.', 89.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed002/'),
('PN-003', 'Cloud Nine Low', 'Ultra-cushioned everyday trainer built for all-day comfort. Reinforced toe cap and heel counter.', 109.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed003/'),
('PN-004', 'Trail Blazer GTX', 'Waterproof hiking shoe with Gore-Tex lining and aggressive rubber outsole. Built for wet terrain.', 159.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed004/'),
('PN-005', 'Retro Court Classic', 'Vintage-inspired low-top basketball shoe. Vulcanised sole and premium leather upper.', 74.99, 'GBP', 'IN_STOCK', true, 'https://www.instagram.com/p/seed005/'),
('PN-006', 'Sprint Spike Elite', 'Competition sprint spike with carbon plate and anatomical fit. Designed for 100m–400m events.', 199.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed006/'),
('PN-007', 'Slip-On Canvas Co.', 'Minimalist canvas slip-on with cushioned footbed. Machine washable.', 39.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed007/'),
('PN-008', 'Hiker Pro Boot', 'Mid-cut leather hiking boot with waterproof membrane. 200g insulation for cold weather.', 219.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed008/'),
('PN-009', 'Mule Slide Luxe', 'Genuine suede mule with padded strap and cork-blend footbed. Handcrafted in Portugal.', 95.00, 'EUR', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed009/'),
('PN-010', 'Chelsea Boot', 'Classic elastic-sided Chelsea boot in full-grain leather. Stacked heel, almond toe.', 185.00, 'GBP', 'IN_STOCK', false, 'https://www.instagram.com/p/seed010/'),
('PN-011', 'Sandal Arch Plus', 'Orthopedic sandal with contoured arch support and adjustable buckle straps.', 59.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed011/'),
('PN-012', 'Platform Lug Boot', 'Chunky lug-sole ankle boot with platform heel. Faux leather, zip closure.', 79.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed012/'),
('PN-013', 'Sock Knit Racer', 'Knitted sock-style racing flat with woven upper. Zero-drop for natural foot position.', 119.00, 'EUR', 'IN_STOCK', false, 'https://www.instagram.com/p/seed013/'),
('PN-014', 'Loafer Penny Classic', 'Genuine calfskin penny loafer with leather sole. A wardrobe staple.', 145.00, 'GBP', 'IN_STOCK', true, 'https://www.instagram.com/p/seed014/'),
('PN-015', 'Indoor Football Boot', 'Flat-rubber indoor football shoe with textured upper for improved ball touch.', 69.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed015/'),
('PN-016', 'Barefoot Walker', 'Zero-drop minimalist shoe with wide toe box. Thin 3mm rubber sole for ground feel.', 89.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed016/'),
('PN-017', 'Rain Boot Pull-On', 'Tall rubber rain boot with fleece lining. 100% waterproof, easy pull-on design.', 55.00, 'CAD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed017/'),
('PN-018', 'Dress Oxford Brogue', 'Full-brogue Oxford in tan Scotch-grain leather. Goodyear-welted construction for resoling.', 249.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed018/'),
('PN-019', 'Espadrille Wedge', 'Jute-wrapped wedge espadrille with canvas upper and ankle tie. Summer essential.', 49.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed019/'),
('PN-020', 'High-Top Court', 'Retro high-top basketball silhouette with padded collar and rubber cupsole.', 99.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed020/'),

-- ── T-SHIRTS / TOPS (PN-021 – PN-040) ────────────────────────────────────────
('PN-021', 'Essential Crew Tee', 'Heavyweight 240gsm cotton crew-neck tee. Pre-shrunk, reinforced stitching at collar and cuffs.', 29.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed021/'),
('PN-022', 'Oversized Drop Tee', 'Boxy drop-shoulder tee in 100% organic cotton. Ribbed collar, raw hem.', 34.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed022/'),
('PN-023', 'Graphic Print Tee', 'Limited-edition artist collaboration tee. Screen-printed on 180gsm cotton.', 44.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed023/'),
('PN-024', 'Long Sleeve Waffle', 'Thermal waffle-knit long sleeve in cotton-modal blend. Slim fit, thumb holes.', 49.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed024/'),
('PN-025', 'Polo Pique Classic', 'Two-button pique polo in breathable cotton. Embroidered logo at chest.', 59.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed025/'),
('PN-026', 'Linen Shirt Relaxed', 'Garment-washed linen shirt with camp collar and single chest pocket. Breezy summer staple.', 69.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed026/'),
('PN-027', 'Oxford Button-Down', 'Classic Oxford cloth button-down with box pleat back and rounded hem. Machine washable.', 79.00, 'GBP', 'IN_STOCK', false, 'https://www.instagram.com/p/seed027/'),
('PN-028', 'Flannel Plaid Shirt', 'Brushed cotton flannel in classic tartan check. Double chest pockets, curved hem.', 64.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed028/'),
('PN-029', 'Ribbed Tank Top', 'Slim-fit ribbed cotton tank. Versatile layering piece for gym or casual wear.', 19.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed029/'),
('PN-030', 'Tie-Dye Vintage Tee', 'Hand-dyed tie-dye tee — each piece unique. 100% cotton, relaxed fit.', 39.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed030/'),
('PN-031', 'Merino Base Layer', 'Fine 18.5-micron merino wool base layer. Temperature-regulating, odour-resistant. Ideal for travel.', 99.00, 'EUR', 'IN_STOCK', true, 'https://www.instagram.com/p/seed031/'),
('PN-032', 'Cropped Utility Shirt', 'Cropped fit utility shirt with four patch pockets and adjustable cuffs.', 54.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed032/'),
('PN-033', 'Henley Long Sleeve', '3-button Henley in heavyweight cotton-polyester blend. Relaxed fit, contrast stitching.', 42.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed033/'),
('PN-034', 'Turtleneck Knit', 'Fine-gauge roll-neck knit in cotton-cashmere blend. Slim profile, minimal construction.', 89.00, 'EUR', 'IN_STOCK', false, 'https://www.instagram.com/p/seed034/'),
('PN-035', 'Quarter-Zip Fleece', 'Anti-pilling micro-fleece quarter-zip. Chin guard, zip garage, two hand pockets.', 74.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed035/'),
('PN-036', 'Printed Camp Shirt', 'Short-sleeve camp-collar shirt with all-over tropical print. Viscose, relaxed fit.', 59.99, 'USD', 'OUT_OF_STOCK', true, 'https://www.instagram.com/p/seed036/'),
('PN-037', 'Rugby Stripe Top', 'Classic rugby-stripe long sleeve in heavyweight cotton jersey. Contrast collar.', 64.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed037/'),
('PN-038', 'Zip-Up Hoodie', 'Garment-dyed full-zip hoodie in 320gsm fleece. Kangaroo pocket, metal zip.', 89.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed038/'),
('PN-039', 'Sleeveless Training Tee', 'Moisture-wicking polyester training singlet with mesh panels for ventilation.', 24.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed039/'),
('PN-040', 'Tech Popover Shirt', 'Stretch-nylon popover shirt with four-way stretch. Wrinkle-resistant, quick-dry.', 109.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed040/'),

-- ── BOTTOMS (PN-041 – PN-055) ─────────────────────────────────────────────────
('PN-041', 'Slim Chino', '98% cotton, 2% elastane slim-fit chino. Five-pocket, concealed button fly.', 69.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed041/'),
('PN-042', 'Carpenter Cargo Pant', 'Relaxed-fit cargo pant with hammer loop, tool pockets, and knee pad inserts.', 84.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed042/'),
('PN-043', 'Wide-Leg Trouser', 'High-rise wide-leg trouser in polyester-viscose blend. Pressed crease, zip fly.', 79.00, 'GBP', 'IN_STOCK', false, 'https://www.instagram.com/p/seed043/'),
('PN-044', 'Selvedge Denim Jeans', '13oz Japanese selvedge denim. Slim straight fit, single-stitch seams, hidden rivets.', 199.99, 'USD', 'OUT_OF_STOCK', true, 'https://www.instagram.com/p/seed044/'),
('PN-045', 'Shorts 5-Inch', 'Stretch-cotton 5-inch inseam shorts. Four-way stretch, internal drawcord, side pockets.', 49.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed045/'),
('PN-046', 'Linen Wide Short', 'Crinkle-linen wide-leg shorts with elasticated waistband and two side pockets.', 44.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed046/'),
('PN-047', 'Jogger Sweatpant', 'French-terry jogger with tapered ankle, contrast side stripe, and zip pockets.', 64.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed047/'),
('PN-048', 'Tech Trail Short', 'Lightweight nylon trail short with built-in brief liner, zip back pocket.', 54.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed048/'),
('PN-049', 'Pleated Wool Trouser', 'Single-pleat trouser in a fine wool-mohair blend. Dry clean only.', 149.00, 'EUR', 'IN_STOCK', true, 'https://www.instagram.com/p/seed049/'),
('PN-050', 'Biker Short', 'High-waist compressive biker short in ribbed nylon. 8-inch inseam.', 34.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed050/'),
('PN-051', 'Waxed Canvas Pant', 'Waxed cotton canvas work pant. Straight fit, reinforced knees and seat.', 119.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed051/'),
('PN-052', 'Track Pant Tearaway', 'Side-snap tearaway track pant in water-repellent nylon. Retro silhouette.', 74.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed052/'),
('PN-053', 'Mini Skirt Tweed', 'Boucle-tweed mini skirt with frayed hem and back zip. Lined.', 89.00, 'GBP', 'IN_STOCK', false, 'https://www.instagram.com/p/seed053/'),
('PN-054', 'Maxi Linen Skirt', 'Floor-length linen skirt with elasticated waistband and front slit.', 69.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed054/'),
('PN-055', 'Denim Cutoff Short', 'Upcycled denim cutoff shorts with raw hem and single back pocket.', 39.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed055/'),

-- ── JACKETS / OUTERWEAR (PN-056 – PN-070) ────────────────────────────────────
('PN-056', 'Puffer Down Jacket', '650-fill-power duck down jacket with recycled shell. Packable into chest pocket.', 249.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed056/'),
('PN-057', 'Waxed Trucker Jacket', 'Waxed cotton trucker jacket with corduroy collar and two chest pockets.', 189.00, 'GBP', 'IN_STOCK', false, 'https://www.instagram.com/p/seed057/'),
('PN-058', 'Raincoat Shell', '2.5L taped-seam rain shell with pit-zip vents and helmet-compatible hood.', 299.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed058/'),
('PN-059', 'Sherpa Fleece Jacket', 'Deep-pile sherpa fleece with contrast lining. Snap closure, two patch pockets.', 119.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed059/'),
('PN-060', 'Leather Moto Jacket', 'Full-grain cowhide moto jacket with asymmetric zip, quilted lining and snap lapels.', 499.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed060/'),
('PN-061', 'Coach Jacket Nylon', 'Lightweight nylon coach jacket with snap placket, rib-knit collar and cuffs.', 89.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed061/'),
('PN-062', 'Wool Overcoat', 'Double-breasted wool-cashmere overcoat. Peak lapel, fully lined, functional button cuffs.', 599.00, 'EUR', 'OUT_OF_STOCK', true, 'https://www.instagram.com/p/seed062/'),
('PN-063', 'Denim Chore Coat', 'Rigid 14oz denim chore coat with three patch pockets and single-stitch seams.', 139.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed063/'),
('PN-064', 'Softshell Hoodie', 'Bonded softshell hoodie with stretch-woven face and micro-fleece backer. Wind-resistant.', 159.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed064/'),
('PN-065', 'Varsity Bomber', 'Wool-body varsity jacket with leather sleeves, rib trim and embroidered chenille patches.', 349.00, 'USD', 'OUT_OF_STOCK', true, 'https://www.instagram.com/p/seed065/'),
('PN-066', 'Quilted Gilet', 'Lightweight quilted vest with synthetic insulation and two zip pockets.', 79.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed066/'),
('PN-067', 'Anorak Pullover', 'Half-zip nylon anorak with kangaroo pocket and contrast hood lining.', 109.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed067/'),
('PN-068', 'Military Field Jacket', 'Cotton-ripstop field jacket with four bellows pockets and drawcord hem.', 169.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed068/'),
('PN-069', 'Trench Coat Classic', 'Double-breasted gabardine trench with storm flap, gun flap, and removable belt.', 449.00, 'GBP', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed069/'),
('PN-070', 'Parka Expedition', 'Extreme-weather parka with 800-fill goose down, fur-trim hood, and snow gaiters. Rated to -40°C.', 799.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed070/'),

-- ── ACCESSORIES (PN-071 – PN-085) ────────────────────────────────────────────
('PN-071', 'Canvas Tote Bag', 'Heavyweight 18oz canvas tote with 30cm gusset and internal zip pocket.', 34.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed071/'),
('PN-072', 'Leather Bifold Wallet', 'Slim bifold wallet in full-grain vegetable-tanned leather. Six card slots, two cash compartments.', 79.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed072/'),
('PN-073', 'Snapback Cap', 'Six-panel structured snapback with embroidered logo and flat brim.', 34.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed073/'),
('PN-074', 'Wool Beanie', 'Ribbed 100% merino wool beanie. Double-thickness cuff, one size fits all.', 29.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed074/'),
('PN-075', 'Leather Belt', 'Full-grain leather belt with solid brass pin buckle. 35mm wide, available in three colours.', 54.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed075/'),
('PN-076', 'Silk Scarf', '90cm square silk twill scarf with hand-rolled edges. Exclusive print.', 120.00, 'EUR', 'OUT_OF_STOCK', true, 'https://www.instagram.com/p/seed076/'),
('PN-077', 'Sunglasses Aviator', 'Polarised glass lenses in stainless steel aviator frame. UV400 protection.', 149.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed077/'),
('PN-078', 'Crossbody Bag', 'Pebbled leather crossbody with magnetic snap closure and adjustable strap.', 189.00, 'GBP', 'IN_STOCK', true, 'https://www.instagram.com/p/seed078/'),
('PN-079', 'Bucket Hat Ripstop', 'Packable nylon ripstop bucket hat with chin strap and UPF50+ rating.', 24.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed079/'),
('PN-080', 'Field Watch', 'Swiss quartz field watch with 40mm brushed steel case and canvas strap. 50m water resistant.', 299.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed080/'),
('PN-081', 'Gloves Leather', 'Cashmere-lined driving gloves in nappa leather. Knuckle perforations, snap closure.', 89.00, 'GBP', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed081/'),
('PN-082', 'Backpack Roll-Top', '25L waxed canvas roll-top backpack with padded laptop sleeve and magnetic side buckles.', 159.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed082/'),
('PN-083', 'Silver Chain Necklace', 'Sterling silver flat-link chain, 60cm. Lobster claw clasp. Hypoallergenic.', 69.99, 'USD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed083/'),
('PN-084', 'Duffle Bag Weekend', '40L cotton canvas duffle with vegetable-tanned leather trim and shoulder strap.', 229.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed084/'),
('PN-085', 'Knit Tie', 'Hand-knit silk tie with square tip. 7cm width. A modern take on a timeless accessory.', 59.00, 'EUR', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed085/'),

-- ── DRESSES / FORMAL (PN-086 – PN-095) ───────────────────────────────────────
('PN-086', 'Midi Wrap Dress', 'Fluid viscose wrap dress with V-neckline and adjustable self-tie belt. Midi length.', 89.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed086/'),
('PN-087', 'Blazer Single-Breasted', 'Slim single-breasted blazer in Italian wool. Notch lapel, half-canvas construction.', 349.00, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed087/'),
('PN-088', 'Slip Dress Satin', 'Bias-cut satin slip dress with adjustable straps and lace trim. Fully lined.', 79.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed088/'),
('PN-089', 'Suit Two-Piece', 'Two-piece suit in stretch-wool twill. Slim blazer with matching slim trouser.', 499.00, 'GBP', 'IN_STOCK', true, 'https://www.instagram.com/p/seed089/'),
('PN-090', 'Maxi Floral Dress', 'Smocked-bodice maxi dress in cotton voile with allover floral print. Tiered skirt.', 99.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed090/'),
('PN-091', 'Formal Dress Shirt', 'Sea Island cotton formal shirt with French cuffs and pleated bib front. Slim fit.', 195.00, 'GBP', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed091/'),
('PN-092', 'Shirt Dress Chambray', 'Knee-length chambray shirt dress with button-through front and belted waist.', 74.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed092/'),
('PN-093', 'Velvet Blazer', 'Cotton-velvet evening blazer in midnight navy. Peak lapel, jetted pockets, satin lining.', 289.00, 'EUR', 'DISCONTINUED', true, 'https://www.instagram.com/p/seed093/'),
('PN-094', 'Cocktail Dress', 'Structured stretch-crepe cocktail dress with cap sleeves and invisible back zip. Knee length.', 149.99, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed094/'),
('PN-095', 'Linen Suit Jacket', 'Unstructured linen summer jacket. Two-button, patch pockets. Breathable and packable.', 229.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed095/'),

-- ── EDGE CASES / UI STRESS TEST (PN-096 – PN-100) ────────────────────────────
('PN-096', 'A', 'Short title, short description.', 9.99, 'USD', 'IN_STOCK', false, 'https://www.instagram.com/p/seed096/'),
('PN-097', 'The Extraordinarily Long-Named Premium Heritage Collection Piece', 'This product has a very long title to test how the product card handles text overflow, wrapping, and truncation across different screen sizes. The card layout should remain intact and not break.', 1499.99, 'USD', 'IN_STOCK', true, 'https://www.instagram.com/p/seed097/'),
('PN-098', 'Zero-Price Test Item', 'This item is priced at zero to verify the price display renders correctly as 0.00 and does not break the layout or show blank.', 0.00, 'USD', 'OUT_OF_STOCK', false, 'https://www.instagram.com/p/seed098/'),
('PN-099', 'Multi-Currency CAD Item', 'Product priced in Canadian dollars to verify that the currency field renders correctly alongside the price across the card and detail page.', 79.99, 'CAD', 'DISCONTINUED', false, 'https://www.instagram.com/p/seed099/'),
('PN-100', 'Featured + Discontinued Edge Case', 'This product is both featured and discontinued — testing that both badges render simultaneously on the detail page without layout issues. The description is intentionally long to stress-test the card height: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 299.99, 'EUR', 'DISCONTINUED', true, 'https://www.instagram.com/p/seed100/');
